const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.dt
	];
};
self.C3_JsPropNameTable = [
	{FundoLoja: 0},
	{TipoCliente: 0},
	{SlotIndex: 0},
	{Estado: 0},
	{Tipo: 0},
	{MoverPara: 0},
	{Cliente: 0},
	{Bancada: 0},
	{TextoProblema: 0},
	{Resposta: 0},
	{Confirmar: 0},
	{TextMoedas: 0},
	{Teclado: 0},
	{PontoEntrada: 0},
	{PontoAtendimento: 0},
	{TextoTempo: 0},
	{Textofeedback: 0},
	{Moedas: 0},
	{Numero1: 0},
	{Numero2: 0},
	{RespostaCorreta: 0},
	{ClientesAtendidos: 0},
	{MaxClientes: 0},
	{ClienteAtivo: 0},
	{Nível: 0},
	{TempoCliente: 0}
];

self.InstanceType = {
	FundoLoja: class extends self.ITiledBackgroundInstance {},
	Cliente: class extends self.ISpriteInstance {},
	Bancada: class extends self.ISpriteInstance {},
	TextoProblema: class extends self.ITextInstance {},
	Resposta: class extends self.ITextInputInstance {},
	Confirmar: class extends self.IButtonInstance {},
	TextMoedas: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	PontoEntrada: class extends self.ISpriteInstance {},
	PontoAtendimento: class extends self.ISpriteInstance {},
	TextoTempo: class extends self.ITextInstance {},
	Textofeedback: class extends self.ITextInstance {}
}